version: '3.1'

services:
  webserver:
    image: webdevops/php-apache-dev:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/app

  mysql:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: test
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev